[package]
name        = "dao-migrator"
authors     = ["Art3mix <art3mix.90@gmail.com>"]
description = "A DAO DAO migrator module for modules."
edition     = { workspace = true }
license = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-std     = { workspace = true, features = ["ibc3"] }
cosmwasm-schema  = { workspace = true }
cw-storage-plus  = { workspace = true }
cw-utils         = { workspace = true }
thiserror        = { workspace = true }
cw2              = { workspace = true }
cw20             = { workspace = true }
dao-interface    = { workspace = true }

dao-dao-core           = { workspace = true, features = ["library"] }
dao-voting             = { workspace = true }
dao-proposal-single    = { workspace = true, features = ["library"] }
dao-voting-cw4         = { workspace = true, features = ["library"] }
cw20-stake             = { workspace = true, features = ["library"] }
dao-voting-cw20-staked = { workspace = true, features = ["library"] }
cw20-base              = { workspace = true, features = ["library"] }

cw-utils-v1                   = { workspace = true }
voting-v1                     = { workspace = true }
cw-core-v1                    = { workspace = true, features = ["library"] }
cw-proposal-single-v1         = { workspace = true, features = ["library"] }
cw20-staked-balance-voting-v1 = { workspace = true, features = ["library"] }
cw20-stake-v1                 = { workspace = true, features = ["library"] }
cw-core-interface-v1          = { workspace = true }
cw4-voting-v1                 = { workspace = true }
cw20-v1                       = { workspace = true }
cw4-v1                        = { workspace = true }

[dev-dependencies]
dao-migrator    = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-multi-test   = { workspace = true }
dao-testing     = { workspace = true }
anyhow          = { workspace = true }
