[package]
name = "nft-controllers"
authors = ["CypherApe cypherape@protonmail.com", "Noah <noah@daodao.zone>"]
description = "A package for managing NFT claims."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-utils = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { workspace = true }
